#exception handling

try:
    x =("bala",'2','3','4') #tuples add 
    x.append('5')
    print(x)
    
except:
    list =["bala",'2','3','4'] #list add ...
    list.append('5')
    print(list)

#else:
    #print("nothing went wrong")
